site_name: DOCUMENTAÇÃO - LICITA BSB
repo_url: https://github.com/unb-mds/LicitaBSB-24.1

extra_css:
  - stylesheets/style.css
nav: 
  - Home: index.md
  - Tutorial - Como Inicializar o Ambiente Virtual: StepByStep/execution.md
  - Arquitetura: Arquitetura/arquitetura.md
  - Jornada de produção: storymap/storymap.md

  - Sprints:
    - Sprint 0:
      - Reunião 1: Atas/Sprint0_reunião1.md
      - Reunião 2: Atas/Sprint0_reunião2.md
    - Sprint 1:
      - Reunião 1: Atas/Sprint1_reunião1.md
      - Reunião 2: Atas/Sprint1_reunião2.md
    - Sprint 2:
      - Reunião 1: Atas/Sprint2_reunião1.md
    - Sprint 3:
      - Reunião 1: Atas/Sprint3_reunião1.md
      - Reunião 2: Atas/Sprint3_reunião2.md
    - Sprint 4:
      - Reunião 1: Atas/Sprint4_reunião1.md
    - Sprint 5:
      - Reunião 1: Atas/Sprint5_reunião1.md
    - Sprint 6:
      - Reunião 1: Atas/Sprint6_reunião1.md
    - Sprint 7:
      - Reunião 1: Atas/Sprint7_reunião1.md
      - Reunião 2: Atas/Sprint7_reunião2.md
    - Sprint 8:
      - Reunião 1: Atas/Sprint8_reunião1.md
    - Sprint 9:
          - Reunião 1: Atas/Sprint9_reunião1.md
  - Materiais de Estudos: Estudos/Estudos.md
  - Ferramentas para o projeto: Ferramentas/ferramentas.md
  - Organização da Equipe: OrganizacaoEquipe/Cargos do Time.md
theme: 
  logo: stylesheets/logo.png
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette: 
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
  icon:
    repo: fontawesome/brands/git-alt
